#!/bin/bash
for i in {1..9}
do
	ping rpi0$i -w 1 > /dev/null
	if  [ $? -eq 0 ]; then
		echo "RPI0$i is responsive"
	else
		echo "RPI0$i is unresponsive"
	fi
done

for i in {10..20}
do

	ping rpi$i -w 1 > /dev/null
	if  [ $? -eq 0 ]; then
		echo "RPI$i is responsive"
	else
		echo "RPI$i is unresponsive"
	fi
done

echo "done"
